on: ["push"]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ASTRONOMER_KEY_ID: ${{ secrets.ASTRO_CLOUD_STAGING_DEPLOYMENT_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRO_CLOUD_STAGING_DEPLOYMENT_KEY_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: echo "hi" >> include/file.txt && pwd && find /home/runner/work/cicdtest/cicdtest/include
      - id: create-box-auth-json-staging
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "box_auth_config.json"
          json: "{}"
          dir: 'include/utils/'
      - uses: astronomer/deploy-action@v0.1
#      - name: docker build
#        run: docker build . -t test && docker run test find /usr/local/airflow/include/